/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.insalyon.p2i2.javaarduino.ihm;

import javax.swing.JComboBox;

/**
 *
 * @author bkermani
 */
public class FenetreAccueil extends javax.swing.JFrame {
    /**
     * Creates new form FenetreAccueil
     */
    FenetreJeu fj;
    public FenetreAccueil() {
        initComponents();
        this.setLocationRelativeTo(null);
        fj = new FenetreJeu();
        fj.setVisible(false);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        titre = new javax.swing.JLabel();
        accordeur = new javax.swing.JButton();
        nomMusique = new javax.swing.JComboBox<>();
        niveau = new javax.swing.JLabel();
        musique = new javax.swing.JLabel();
        niveauChoisi = new javax.swing.JLabel();
        tempo = new javax.swing.JRadioButton();
        rythmeAdapte = new javax.swing.JRadioButton();
        choixTempo = new javax.swing.JTextField();
        tempoConseille = new javax.swing.JLabel();
        valeurConseille = new javax.swing.JLabel();
        jouer = new javax.swing.JButton();
        analyseDonnees = new javax.swing.JButton();

        buttonGroup.add(tempo);
        buttonGroup.add(rythmeAdapte);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titre.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        titre.setText("Apprentissage Guitare");

        accordeur.setText("Accordeur");
        accordeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accordeurActionPerformed(evt);
            }
        });

        nomMusique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomMusiqueActionPerformed(evt);
            }
        });

        niveau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        niveau.setText("Difficulté :");

        musique.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        musique.setText("Musique :");

        tempo.setText("Tempo : d =");
        tempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempoActionPerformed(evt);
            }
        });

        rythmeAdapte.setText("Rythme adapté");
        rythmeAdapte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rythmeAdapteActionPerformed(evt);
            }
        });

        choixTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixTempoActionPerformed(evt);
            }
        });

        tempoConseille.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tempoConseille.setText("tempo conseillé: d =");

        valeurConseille.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jouer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jouer.setText("Jouer");
        jouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouerActionPerformed(evt);
            }
        });

        analyseDonnees.setText("Analyse de Données");
        analyseDonnees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyseDonneesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accordeur)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(musique, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(analyseDonnees, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(nomMusique, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(niveauChoisi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rythmeAdapte)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tempoConseille)
                                        .addGap(18, 18, 18)
                                        .addComponent(valeurConseille)
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tempo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(choixTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jouer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titre)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accordeur, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(analyseDonnees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomMusique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musique, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niveauChoisi, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choixTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempoConseille)
                    .addComponent(valeurConseille, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rythmeAdapte, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jouer, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempoActionPerformed

    private void choixTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixTempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choixTempoActionPerformed

    private void rythmeAdapteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rythmeAdapteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rythmeAdapteActionPerformed

    private void accordeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accordeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accordeurActionPerformed

    private void jouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouerActionPerformed
        //Permet d'ouvrir la fenêtre de jeu et de cacher cette fenêtre lors de l'appui du bouton "Jouer"
        this.dispose();
        fj.setVisible(true);
    }//GEN-LAST:event_jouerActionPerformed

    private void analyseDonneesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyseDonneesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analyseDonneesActionPerformed

    private void nomMusiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomMusiqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomMusiqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accordeur;
    private javax.swing.JButton analyseDonnees;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JTextField choixTempo;
    private javax.swing.JButton jouer;
    private javax.swing.JLabel musique;
    private javax.swing.JLabel niveau;
    private javax.swing.JLabel niveauChoisi;
    private javax.swing.JComboBox<String> nomMusique;
    private javax.swing.JRadioButton rythmeAdapte;
    private javax.swing.JRadioButton tempo;
    private javax.swing.JLabel tempoConseille;
    private javax.swing.JLabel titre;
    private javax.swing.JLabel valeurConseille;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getNomMusique() {
        return nomMusique;
    }
}
